image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
configuration:
  - Debug
before_build:
  - cmd: nuget install NUnit.Console -Version 3.7.0 -OutputDirectory tools
  - cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - cmd: nuget restore
  - cmd: choco install codecov
build:
  project: CDP4-Server.sln
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
      - AppVeyorExclusion